### ISSUE TITLE
Should listener.failure be called when the circuit is closed and a call fails?

### ISSUE THREAD

**Issue by sj175** [danielfm/pybreaker#16]
When the circuit breaker's state is closed and the call to the wrapped function fails the listener.failure function is not called because an exception is thrown in CircuitClosedState.on_failure. Is this behaviour intentional?

The block below is from the CircuitBreakerState class:
```python
    def _handle_error(self, exc):
        """
        Handles a failed call to the guarded operation.
        """
        if self._breaker.is_system_error(exc):
            self._breaker._inc_counter()
            self.on_failure(exc)
            for listener in self._breaker.listeners:
                listener.failure(self._breaker, exc)
        else:
            self._handle_success()
        raise exc
```

**Comment by danielfm** [comment]
Good catch.

AFAIK this behavior is not intentional, seems more like a bug to me.

**Comment by danielfm** [comment]
Just pushed a new version, that hopefully fixes this issue, can you take some time to test it?

**Comment by sj175** [comment]
Sure, all my tests pass at the moment but it's still fairly early in my development process.

**Comment by sj175** [comment]
Actually, it looks like Redis is now a dependency, it wasn't before. If that was intentional, that's fine. Otherwise, my tests are now broken.

**Comment by danielfm** [comment]
Redis is an _optional_ dependency, in case you enable the Redis backing. You should be able to use it without it though.

**Comment by sj175** [comment]
I get `raise ImportError("CircuitRedisStorage can only be used if the required dependencies exist")
ImportError: CircuitRedisStorage can only be used if the required dependencies exist` as soon as I import pybreaker.

**Comment by danielfm** [comment]
This is a bug; redis should not be required to use pybreaker.

I'll see what I can do.

**Comment by phillbaker** [comment]
Ouch. Sorry about that. I'll take a look tonight.

**Comment by danielfm** [comment]
@sj175 can you please try 0.3.3 to see if the last PR fixes the issue? Feel free to reopen this in case it didn't.

**Comment by sj175** [comment]
That's fixed. Brilliant, thank you!
