### ISSUE TITLE
thread safety ?

### ISSUE THREAD

**Issue by gst** [danielfm/pybreaker#3]
Hi,

not an issue but a question:

is it safe to use the same breaker instance (CircuitBreaker) by multiple threads, possibly concurrently (modulo GIL ofcourse) ?

thx for the lib :)

**Comment by gst** [comment]
I answer to myself : 

given a circuit breaker is associated with a thread lock and that the lock is taken whenever a call is done on/with the circuit breaker then yes it's safe to use the same breaker instance with multiple threads, concurrently running.

But then any combination of threads using the same circuit will be limited by this : only one "call" at a time will be processed given this lock.  

But what if we don't want this behavior but still want to use/share the same breaker between multiple threads ?

I'm thinking : there could simply be a lock-less version of the circuit breaker..  which could be the "base" one, and the lock version of the circuit breaker would simply subclass the lock-less version and add the lock and use it..

wdyt?

**Comment by danielfm** [comment]
Yes, I think that's a great idea!

**Comment by gst** [comment]
I've think again about it : probably the lock should still be more than necessary (for the circuit breaker failure count), but it's not necessary to have it locked while you actually call/execute the "wrapped" function..

**Comment by gst** [comment]
the next step would be to propose a PR I guess ;)

**Comment by danielfm** [comment]
That would be nice! :smile:

**Comment by robertlagrant** [comment]
@gst @danielfm did this get any further?

**Comment by gst** [comment]
not on my side sorry. not anymore user of pybreaker.
