### ISSUE TITLE
proposal: adding a name property to CircuitBreaker

### ISSUE THREAD

**Issue by chrisvaughn** [danielfm/pybreaker#30]
Thanks for the great library.  I'm adding logging to our use of circuit breakers so that we can see just how often states are changing.  To make our logs more informative I've subclassed `CircuitBreaker` to add a "name" property that I can use in logs, statsd counters, etc.  Is there any interest in adding this to `CircuitBreaker`? If so, I'll create a PR.

**Comment by danielfm** [comment]
Yes, please! :)
