### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by Kludex** [danielfm/pybreaker#65]
I'll be opening some PRs on this project, as I intend to use it extensively.

I'd like to know if this package is/will be actively maintained, if I should fork it - I'll still intend to submit the PRs here if that's the case - or if I can help here with the maintenance. 🙏 

In any case, thanks so much for this package! 🙌

**Comment by danielfm** [comment]
I no longer work with Python, so I no longer need this package for my own needs, but I'll continue to maintain it and continue to merge contributions that I think it would benefit its users.
