### ISSUE TITLE
README sentence left hanging

### ISSUE THREAD

**Issue by eliasdorneles** [danielfm/pybreaker#83]
Hello! :wave: 

I'm discovering the library, thanks for sharing! =)

Here to report an unfinished sentence in the README: https://github.com/danielfm/pybreaker/blob/main/README.rst?plain=1#L204

> By default, when the circuit breaker trips, it w

I'm curious, what's the end of that sentence? :smile:

**Comment by danielfm** [comment]
Now I'm curious too. It's been a long time, I don't remember.

I'll remove that.

**Comment by danielfm** [comment]
Done. If I remember what was that about, I'll include it again.
