### ISSUE TITLE
Contextmanager / `with` API?

### ISSUE THREAD

**Issue by martijnthe** [danielfm/pybreaker#85]
Would you be open to accepting a PR to make `CircuitBreaker` also possible to use like so:

```
with circuit_breaker:
   do_the_thing_that_can_fail()
```

I think this is slightly nicer than the `.call(...)` API.

Thanks for creating & maintaining this library!

**Comment by danielfm** [comment]
Sure, as long as we don't break compatibility with current features!

Also, if the README is updated to cover the improvements, that's even better.

**Comment by martijnthe** [comment]
> Sure, as long as we don't break compatibility with current features!
> 
> Also, if the README is updated to cover the improvements, that's even better.

OK, great.

I took a stab at it here:
https://github.com/danielfm/pybreaker/pull/87
