### ISSUE TITLE
(🐞) incorrect typing for exclude argument

### ISSUE THREAD

**Issue by houbie** [danielfm/pybreaker#90]
Exclude is defined as:
`exclude: Sequence[Type[ExceptionType]] | None = None,`
but it can also be a callable. Mypy complains about following code (when not ignoring the type error):
```python
pybreaker.CircuitBreaker(
        fail_max=CIRCUIT_BREAKER_MAX_FAIL,
        reset_timeout=CIRCUIT_BREAKER_RESET_TIMEOUT,
        # don't trip circuit on client errors, except 429 (too Many Requests)
        exclude=[  # type: ignore[arg-type]
            lambda e: isinstance(e, HTTPError)
            and e.response.status_code < 500
        ],
    )
```

**Comment by danielfm** [comment]
Thanks for the report. Would you be willing to submit a pull request to fix the issue?

**Comment by houbie** [comment]
I'll give it a try...

**Comment by houbie** [comment]
pre-commit is giving errors :(

I could modernise the python setup like [this](https://github.com/pyprojectx/pyprojectx), guaranteeing reproducible builds. This would also relieve potential contributors from having to manually install tools like pre-commit, black, etc., and they can't forget to run `pre-commit install` anymore.

Would consider such a pull request?

**Comment by danielfm** [comment]
Sure, that would be awesome!

**Comment by houbie** [comment]
I created a draft PR that sets up tooling and fixes the type hints, but I suggest to take it further:
- add ruff for static code analysis (and use it as replacement for black and isort)
- use pytest to simplify test code and type check the test code so that typechecks.py can be removed again
- use pyproject.toml for project meta instead of setup.py

Let me know what you think of it

**Comment by danielfm** [comment]
I'm okay with dropping support for py3.7.

**Comment by houbie** [comment]
finished the PR:
- [successful build](https://github.com/houbie/pybreaker/actions/workflows/build.yml)
- [successful publish to test pypi](https://test.pypi.org/project/pybreaker/)
- you can publish to pypi with `./pw flit publish` using settings from ~/.pypirc
